name: Build
on: [push, pull_request]

jobs:
  buildCemuStub:
    runs-on: windows-2019
    steps:
    - name: Checkout current build target
      uses: actions/checkout@v2
      with:
        path: 'Bizhawk-Vanguard'
    - name: Checkout RTCV peer dependency
      uses: actions/checkout@v2
      with:
        repository: 'ircluzar/RTCV'
        ref: '505'
        path: 'RTCV'
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Restore packages
      run: nuget restore '.\Bizhawk-Vanguard\Real-Time Corruptor\BizHawk_RTC\BizHawk.sln'
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Build with MSBuild
      run: msbuild '.\Bizhawk-Vanguard\Real-Time Corruptor\BizHawk_RTC\BizHawk.sln'
