name: Build
on: [push, pull_request]

jobs:
  buildBizhawk:
    runs-on: windows-2019
    steps:
    - name: Checkout current build target
      uses: actions/checkout@v2
      with:
        path: 'Bizhawk-Vanguard'
    - name: Checkout RTCV peer dependency
      uses: actions/checkout@v2
      with:
        repository: 'redscientistlabs/RTCV'
        ref: '506v2'
        path: 'RTCV'
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Restore packages in RTCV
      run: msbuild /t:restore '.\RTCV\'
    - name: Restore packages in Bizhawk-Vanguard
      run: msbuild /t:restore '.\Bizhawk-Vanguard\Real-Time Corruptor\BizHawk_RTC\BizHawk.sln'
    - name: Build with MSBuild
      run: msbuild '.\Bizhawk-Vanguard\Real-Time Corruptor\BizHawk_RTC\BizHawk.sln'
